services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - $VOLUME_BASE_PATH/transmission_config:/config
      - $VOLUME_BASE_PATH/jellyfin_data/downloads:/downloads
    expose:
      - 9091
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.$GATEWAY_HOST`)
      - traefik.http.routers.transmission.entrypoints=web,websecure
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.routers.transmission.middlewares=authelia@docker
      - traefik.http.services.transmission.loadbalancer.server.port=9091
    restart: unless-stopped
    networks:
      - home-lab
networks:
  home-lab:
