version: "3.8"
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.glance.rule=Host(`$GATEWAY_HOST`)
      - traefik.http.routers.glance.entrypoints=web,websecure
      - traefik.http.routers.glance.tls.certresolver=letsencrypt
      - traefik.http.services.glance.loadbalancer.server.port=8080
    volumes:
      - ./config:/app/config
    expose:
      - 8080
    networks:
      - home-lab
networks:
  home-lab:
    driver: bridge
