services:
  homeassistant:
    container_name: homeassistant
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_CMD_WAIT_FOR_SERVICES=1
      - S6_SERVICES_READYTIME=50
      - WHEELS_LINKS=https://wheels.home-assistant.io/musllinux/
      - S6_SERVICES_GRACETIME=220000
    image: homeassistant/home-assistant:latest
    volumes:
      - $VOLUME_BASE_PATH/homeassistant_config:/config
    working_dir: /config
    restart: unless-stopped
    network_mode: host
networks: {}
