services:
  lusci:
    image: eclipse-temurin:21-jre-alpine
    container_name: lusci
    volumes:
      - $VOLUME_BASE_PATH/lusci_data/lusci.jar:/opt/app/lusci.jar
    command:
      - java
      - -jar
      - /opt/app/lusci.jar
    env_file:
      - ../.env
    networks:
      - home-lab
    restart: unless-stopped
networks:
  home-lab:
