- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 600
  register: reboot_status

- name: Wait for the machine to become reachable
  ansible.builtin.wait_for:
    port: 22
    delay: 10
    timeout: 300
  when: reboot_status.changed

- name: Run hello-world container to verify Docker installation
  ansible.builtin.command:
    cmd: docker run hello-world
