services:
  youtubedl:
    container_name: youtubedl
    expose:
      - 8080
    volumes:
      - $VOLUME_BASE_PATH/jellyfin_data/downloads:/youtube-dl
    image: kmb32123/youtube-dl-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.youtubedl.rule=Host(`youtubedl.$GATEWAY_HOST`)
      - traefik.http.routers.youtubedl.entrypoints=web,websecure
      - traefik.http.routers.youtubedl.tls.certresolver=letsencrypt
      - traefik.http.routers.youtubedl.middlewares=authelia@docker
      - traefik.http.services.youtubedl.loadbalancer.server.port=8080
    networks:
      - home-lab
    restart: unless-stopped
networks:
  home-lab:
