version: '3.8'
services:
  fallback:
    container_name: 'fallback'
    restart: unless-stopped
    image: python:3.11-slim
    volumes:
      - ./app.py:/app.py
    expose:
      - 4444
    command: python /app.py
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
