include:
  - ./adguardhome/compose.yml
  - ./filebrowser/compose.yml
  - ./glance/compose.yml
  - ./homeassistant/compose.yml
  - ./isponsorblocktv/compose.yml
  - ./lusci/compose.yml
  - ./neon-drift-server/compose.yml
  - ./openspeedtest/compose.yml
  - ./traefik/compose.yml
  - ./uptimekuma/compose.yml
  - ./ragtech-ups-monitor/compose.yml
