services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DESTINATION_IP=$DESTINATION_IP
      - GATEWAY_HOST=$GATEWAY_HOST
