stream {
  map $ssl_preread_server_name $backend {
    jellyfin.homelab.vini.center $DESTINATION_IP:443;
    ha.homelab.vini.center $DESTINATION_IP:443;
    default 127.0.0.1:4444;
  }

  server {
    listen 443;
    proxy_pass $backend;
    ssl_preread on;
  }
}
