theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Homelab
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Home Assistant
                url: https://ha.homelab.vini.center/
                check-url: http://172.17.0.1:8123
                icon: di:home-assistant
              - title: Jellyfin
                url: https://jellyfin.homelab.vini.center/
                check-url: http://jellyfin:8096
                icon: di:jellyfin
              - title: qBittorrent (VPN Only)
                url: https://qbittorrent.homelab.vini.center/
                check-url: http://qbittorrent:8080
                icon: di:qbittorrent
              - title: Sonarr (VPN Only)
                url: https://sonarr.homelab.vini.center/
                check-url: http://sonarr:8989
                icon: di:sonarr
              - title: Radarr (VPN Only)
                url: https://radarr.homelab.vini.center/
                check-url: http://radarr:7878
                icon: di:radarr
              - title: Prowlarr (VPN Only)
                url: https://prowlarr.homelab.vini.center/
                check-url: http://prowlarr:9696
                icon: di:prowlarr
              - title: Bazarr (VPN Only)
                url: https://bazarr.homelab.vini.center/
                check-url: http://bazarr:6767
                icon: di:bazarr
              - title: File Browser (VPN Only)
                url: https://filebrowser.homelab.vini.center/
                check-url: http://filebrowser:80
                icon: di:filebrowser
              - title: Traefik (VPN Only)
                url: https://traefik.homelab.vini.center/
                check-url: http://traefik:8080
                icon: di:traefik
              - title: Uptimekuma (VPN Only)
                url: https://uptime.homelab.vini.center/
                check-url: http://uptimekuma:3001
                icon: di:uptime-kuma
              - title: OpenSpeedTest (VPN Only)
                url: https://speedtest.homelab.vini.center/
                check-url: http://openspeedtest:3000
                icon: di:openspeedtest

          - type: bookmarks
            groups:
              - title: Infrastructure
                links:
                  - title: Tailscale Login
                    url: https://login.tailscale.com
                  - title: Oracle Cloud Infrastructure 
                    url: https://www.oracle.com/cloud/sign-in.html
