theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Homelab
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Public Services
            sites:
              - title: Home Assistant
                url: https://ha.${GATEWAY_HOST}/
                check-url: http://172.17.0.1:8123
                icon: di:home-assistant
              - title: Jellyfin
                url: https://jellyfin.${GATEWAY_HOST}/
                check-url: http://jellyfin:8096
                icon: di:jellyfin
              - title: Uptimekuma
                url: https://uptime.${GATEWAY_HOST}/
                check-url: http://uptimekuma:3001
                icon: di:uptime-kuma

          - type: monitor
            cache: 1m
            title: VPN-Only Services
            sites:
              - title: qBittorrent
                url: https://qbittorrent.${GATEWAY_HOST}/
                check-url: http://qbittorrent:8080
                icon: di:qbittorrent
              - title: Sonarr
                url: https://sonarr.${GATEWAY_HOST}/
                check-url: http://sonarr:8989
                icon: di:sonarr
              - title: Radarr
                url: https://radarr.${GATEWAY_HOST}/
                check-url: http://radarr:7878
                icon: di:radarr
              - title: Prowlarr
                url: https://prowlarr.${GATEWAY_HOST}/
                check-url: http://prowlarr:9696
                icon: di:prowlarr
              - title: Bazarr
                url: https://bazarr.${GATEWAY_HOST}/
                check-url: http://bazarr:6767
                icon: di:bazarr
              - title: File Browser
                url: https://filebrowser.${GATEWAY_HOST}/
                check-url: http://filebrowser:80
                icon: di:filebrowser
              - title: Traefik
                url: https://traefik.${GATEWAY_HOST}/
                check-url: http://traefik:8080
                icon: di:traefik
              - title: OpenSpeedTest
                url: https://speedtest.${GATEWAY_HOST}/
                check-url: http://openspeedtest:3000
                icon: di:openspeedtest
              - title: Adguardhome
                url: https://adguardhome.${GATEWAY_HOST}/
                check-url: http://adguardhome:3000
                icon: di:adguard-home

          - type: bookmarks
            groups:
              - title: Infrastructure
                links:
                  - title: Tailscale Login
                    url: https://login.tailscale.com
                  - title: Oracle Cloud Infrastructure 
                    url: https://www.oracle.com/cloud/sign-in.html
